---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and test-lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test2
        run: docker-compose run --rm app sh -c "python manage.py test2""
